In [1]:
import numpy as np

x = np.array([1, 2, 3])
print(x)


[1 2 3]


In [2]:
print(x, x.shape, x.size)

[1 2 3] (3,) 3


In [6]:
y = np.array([[1, 2, 3], [1, 3, 4], [1, 5, 6]])
print("shape: ", y.shape)
print("size: ", y.size)
print("type: ", y.dtype)
print(y)

shape:  (3, 3)
size:  9
type:  int32
[[1 2 3]
 [1 3 4]
 [1 5 6]]


In [19]:
y = np.array([[[1,2], [1,2.3]], [[1,2], [2,5]]], dtype="int64")
print("shape: ", y.shape)
print("size: ", y.size)
print("dtype: ", y.dtype)
print("type: ", type(y))
print(y)

shape:  (2, 2, 2)
size:  8
dtype:  int64
type:  <class 'numpy.ndarray'>
[[[1 2]
  [1 2]]

 [[1 2]
  [2 5]]]


In [22]:
z = np.zeros([2,3], dtype="int64")
print(z)

[[0 0 0]
 [0 0 0]]


In [26]:
z = np.eye(5, dtype="float")
print(z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
z = np.diag([10, 20, 30])
print(z)

[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


In [31]:
z = np.full([5,5], 5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [33]:
z = np.ones((2,3))
print(z)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
a = np.arange(2, 10)
print(a)

[2 3 4 5 6 7 8 9]


In [37]:
a = np.arange(2, 10, 2.35)
print(a)

[2.   4.35 6.7  9.05]


In [38]:
a = np.arange(2, 3, 2.35)
print(a)

[2.]


In [39]:
a = np.arange(2, 2, 2.35)
print(a)

[]


In [43]:
a = np.arange(2, 14, 2).reshape(2,3)
print(a)

[[ 2  4  6]
 [ 8 10 12]]


In [46]:
a = np.arange(2, 14, 2.2).reshape(2,3)
print(a)

[[ 2.   4.2  6.4]
 [ 8.6 10.8 13. ]]


In [48]:
a = np.linspace(2, 10, 6)
print(a)

[ 2.   3.6  5.2  6.8  8.4 10. ]


In [49]:
a = np.linspace(2, 10, 16)
print(a)

[ 2.          2.53333333  3.06666667  3.6         4.13333333  4.66666667
  5.2         5.73333333  6.26666667  6.8         7.33333333  7.86666667
  8.4         8.93333333  9.46666667 10.        ]


In [53]:
a = np.linspace(2, 10, 16).reshape(4,4)
print(a)

[[ 2.          2.53333333  3.06666667  3.6       ]
 [ 4.13333333  4.66666667  5.2         5.73333333]
 [ 6.26666667  6.8         7.33333333  7.86666667]
 [ 8.4         8.93333333  9.46666667 10.        ]]


In [54]:
a = np.linspace(2, 10, 16, endpoint=False)
print(a)

[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [55]:
a = np.linspace(2, 10, 16, endpoint=False).reshape(4,4)
print(a)

[[2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]
 [6.  6.5 7.  7.5]
 [8.  8.5 9.  9.5]]


In [58]:
a = np.random.normal(0, 0.01, 3)
print(a)
print("shape: ", a.shape)
print("mean: ", a.mean())
print("max: ", a.max())
print("min: ", a.min())
print("dtype: ", a.dtype)
print("type: ", type(a))

[-0.00358984  0.00930595 -0.00290926]
shape:  (3,)
mean:  0.0009356206522800913
max:  0.009305952620101718
min:  -0.0035898350598861433
dtype:  float64
type:  <class 'numpy.ndarray'>


In [59]:
a = np.random.normal(0, 0.01, size=(3,3))
print(a)
print("shape: ", a.shape)
print("mean: ", a.mean())
print("max: ", a.max())
print("min: ", a.min())
print("dtype: ", a.dtype)
print("type: ", type(a))

[[ 0.01087158  0.00827602 -0.00123448]
 [-0.00298055 -0.00151317 -0.00214627]
 [-0.02567285 -0.01555921  0.01392291]]
shape:  (3, 3)
mean:  -0.001781779949149209
max:  0.013922908118189577
min:  -0.025672851056202328
dtype:  float64
type:  <class 'numpy.ndarray'>


In [63]:
a = np.random.normal(0, 1, size=(3,3))
print(a)
print("shape: ", a.shape)
print("mean: ", a.mean())
print("max: ", a.max())
print("min: ", a.min())
print("dtype: ", a.dtype)
print("type: ", type(a))

[[-1.14315824  0.79093614  0.77751749]
 [ 0.72364947  0.76003215 -0.77229194]
 [-0.35257984 -0.42001715  1.25802899]]
shape:  (3, 3)
mean:  0.18023522856256502
max:  1.2580289892982963
min:  -1.1431582376387595
dtype:  float64
type:  <class 'numpy.ndarray'>


In [64]:
a = np.arange(5)
print(a)
print(a[0])
print(a[-3])

[0 1 2 3 4]
0
2


In [45]:
a = np.arange(6).reshape(2,3)
print(a,"\n")
print(a[0], "\n")
print(a[-2], "\n")
print(a[0,0], "\n")
print(a[1,2], "\n")

[[0 1 2]
 [3 4 5]] 

[0 1 2] 

[0 1 2] 

0 

5 



In [46]:
a = np.arange(6).reshape(2,3)
print(a,"\n")

a[0] = 5
print(a)

[[0 1 2]
 [3 4 5]] 

[[5 5 5]
 [3 4 5]]


In [49]:
a = np.arange(25).reshape(5,5)
print(a,"\n")
a[0] = 5
print(a,"\n")
a[0,1] = 9
print(a,"\n")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 5  5  5  5  5]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 5  9  5  5  5]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 



In [48]:
a = np.arange(25).reshape(5,5)
print(a,"\n")
b = np.append(a, [[2, 2, 2, 2, 2]], axis=0)
print(b,"\n")
b = np.append(a, [[3],[3],[3],[3],[3]], axis=1)
print(b,"\n")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [ 2  2  2  2  2]] 

[[ 0  1  2  3  4  3]
 [ 5  6  7  8  9  3]
 [10 11 12 13 14  3]
 [15 16 17 18 19  3]
 [20 21 22 23 24  3]] 



In [50]:
a = np.arange(25).reshape(5,5)
print(a,"\n")
b = np.delete(a, [0,1])
print(b,"\n")
b = np.delete(a, 0)
print(b,"\n")
b = np.delete(a, 0, axis=0)
print(b,"\n")
b = np.delete(a, 0, axis=1)
print(b,"\n")
b = np.delete(a, 1, axis=1)
print(b,"\n")
b = np.delete(a, [0,1], axis=1)
print(b,"\n")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]] 

[[ 0  2  3  4]
 [ 5  7  8  9]
 [10 12 13 14]
 [15 17 18 19]
 [20 22 23 24]] 

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]] 



In [51]:
a = np.arange(25).reshape(5,5)
print(a,"\n")
b = np.insert(a, 1, [2, 2, 2, 2, 2], axis=0)
print(b,"\n")
b = np.insert(a, 4, [3,3,3,3,3], axis=1)
print(b,"\n")
b = np.insert(a, 3, [[3],[3],[3],[3],[3]], axis=1)
print(b,"\n")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 2  2  2  2  2]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  1  2  3  3  4]
 [ 5  6  7  8  3  9]
 [10 11 12 13  3 14]
 [15 16 17 18  3 19]
 [20 21 22 23  3 24]] 

[[ 0  1  2  3  3  3  3  3  3  4]
 [ 5  6  7  3  3  3  3  3  8  9]
 [10 11 12  3  3  3  3  3 13 14]
 [15 16 17  3  3  3  3  3 18 19]
 [20 21 22  3  3  3  3  3 23 24]] 



In [52]:
a = np.arange(9).reshape(3,3)
print(a,"\n")
b = np.arange(9, 18).reshape(3,3)
print(b,"\n")
c = np.vstack((a,b))
print(c,"\n")
c = np.vstack((b,a))
print(c,"\n")

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 9 10 11]
 [12 13 14]
 [15 16 17]] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]] 

[[ 9 10 11]
 [12 13 14]
 [15 16 17]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]] 



In [53]:
a = np.arange(6).reshape(2,3)
print(a,"\n")
b = np.arange(9, 15).reshape(2,3)
print(b,"\n")
c = np.hstack((a,b))
print(c,"\n")
c = np.hstack((b,a))
print(c,"\n")

[[0 1 2]
 [3 4 5]] 

[[ 9 10 11]
 [12 13 14]] 

[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]] 

[[ 9 10 11  0  1  2]
 [12 13 14  3  4  5]] 



In [54]:
a = np.arange(9).reshape(3,3)
print(a,"\n")
b = a[1:]
print(b,"\n")
b = a[:1]
print(b,"\n")
b = a[:, 1:]
print(b,"\n")
b = a[1:, 1:]
print(b,"\n")
b = a[0:1, 1:]
print(b,"\n")
b = a[0:, 1:]
print(b,"\n")


[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[3 4 5]
 [6 7 8]] 

[[0 1 2]] 

[[1 2]
 [4 5]
 [7 8]] 

[[4 5]
 [7 8]] 

[[1 2]] 

[[1 2]
 [4 5]
 [7 8]] 



In [55]:
a = np.arange(25).reshape(5,5)
print(a,"\n")
b = a[2:, 1:]
print(b,"\n")
b[1,2] = 99
print(b,"\n")
print(a,"\n")
b[1:2] = 99
print(b,"\n")
print(a,"\n")


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]] 

[[11 12 13 14]
 [16 17 99 19]
 [21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 99 19]
 [20 21 22 23 24]] 

[[11 12 13 14]
 [99 99 99 99]
 [21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 99 99 99 99]
 [20 21 22 23 24]] 



In [56]:
a = np.arange(25).reshape(5,5)
print(a,"\n")
b = np.copy(a[2:, 1:])
print(b,"\n")
b[1,2] = 99
print(b,"\n")
print(a,"\n")
b[1:2] = 99
print(b,"\n")
print(a,"\n")
b = a[2:, 1:].copy()
print(b,"\n")
b[1,2] = 99
print(b,"\n")
print(a,"\n")


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]] 

[[11 12 13 14]
 [16 17 99 19]
 [21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[11 12 13 14]
 [99 99 99 99]
 [21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]] 

[[11 12 13 14]
 [16 17 99 19]
 [21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 



In [57]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We create a rank 1 ndarray that will serve as indices to select elements from X
indices = np.array([1,3])

print(X, "\n")
print(indices, "\n")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[1 3] 



In [59]:
# to get specific rows and/or columns

# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[indices,:]

# We use the indices ndarray to select the 2nd and 4th column of X
Z = X[:, indices]

print(Y, "\n")
print(Z, "\n")

[[ 5  6  7  8  9]
 [15 16 17 18 19]] 

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]] 



a = np.arange(9).reshape(3,3)

In [58]:
import numpy as np
a = np.arange(9).reshape(3,3)
print(a, "\n")
a  = np.diag([[2,3], [3,4]])
print(a, "\n")
a  = np.diag([2,3,3,4])
print(a, "\n")
a = np.arange(25).reshape(5,5)
print(a, "\n")
b = np.diag(a)
print(b, "\n")
b = np.diag(a, 0)
print(b, "\n")
b = np.diag(a, -1)
print(b, "\n")
b = np.diag(a, 3)
print(b, "\n")
b = np.unique(a)
print(b, "\n")
a[0,1] = 5
a[2:3] = 9
print(a, "\n")
b = np.unique(a)
print(b, "\n")


[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[2 4] 

[[2 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 4]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[ 0  6 12 18 24] 

[ 0  6 12 18 24] 

[ 5 11 17 23] 

[3 9] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24] 

[[ 0  5  2  3  4]
 [ 5  6  7  8  9]
 [ 9  9  9  9  9]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[ 0  2  3  4  5  6  7  8  9 15 16 17 18 19 20 21 22 23 24] 



In [60]:
a = np.arange(36).reshape(6,6)
print(a, "\n")
b = a[(a>10)]
print(b, "\n")
b = a[(a > 10) & (a < 15)]
print(b, "\n")


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]] 

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35] 

[11 12 13 14] 



In [61]:
a = np.arange(36).reshape(6,6)
print(a, "\n")
b = np.arange(20, 56, 3).reshape(4,3)
print(b, "\n")
c = np.intersect1d(a,b)
print(c, "\n")
c = np.union1d(a,b)
print(c, "\n")
c = np.setdiff1d(a,b)
print(c, "\n")

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]] 

[[20 23 26]
 [29 32 35]
 [38 41 44]
 [47 50 53]] 

[20 23 26 29 32 35] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 38 41 44 47 50 53] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 21 22 24 25
 27 28 30 31 33 34] 



In [34]:
a = np.random.randint(1,23, size=(5,5))
print(a, "\n")
b = a.sort()
print(b, "\n")
print(a, "\n")

[[15  6  7 19  1]
 [ 3 11  3 11 20]
 [15  7 22  4 13]
 [18  2 22  4  3]
 [ 5 16  6  1 15]]

None

[[ 1  6  7 15 19]
 [ 3  3 11 11 20]
 [ 4  7 13 15 22]
 [ 2  3  4 18 22]
 [ 1  5  6 15 16]]



In [62]:
a = np.random.randint(1,23, size=(5,5))
print(a, "\n")
b = np.sort(a)
print(b, "\n")
print(a, "\n")
b = np.sort(a, axis=1)
print(b, "\n")
b = np.sort(a, axis=0)
print(b, "\n")

[[17 12 19  4 21]
 [10 14 12  6 14]
 [17 12 17 21 18]
 [16 17 22  7 10]
 [19 10 11 22  2]] 

[[ 4 12 17 19 21]
 [ 6 10 12 14 14]
 [12 17 17 18 21]
 [ 7 10 16 17 22]
 [ 2 10 11 19 22]] 

[[17 12 19  4 21]
 [10 14 12  6 14]
 [17 12 17 21 18]
 [16 17 22  7 10]
 [19 10 11 22  2]] 

[[ 4 12 17 19 21]
 [ 6 10 12 14 14]
 [12 17 17 18 21]
 [ 7 10 16 17 22]
 [ 2 10 11 19 22]] 

[[10 10 11  4  2]
 [16 12 12  6 10]
 [17 12 17  7 14]
 [17 14 19 21 18]
 [19 17 22 22 21]] 



In [74]:
a = np.arange(1, 50, 2).reshape(5,5)
print(a,"\n")
b = np.random.randint(1,28, size=(5,5))
print(b, "\n")
c = a + b
print(c, "\n")
print(np.add(a,b), "\n")
print(np.subtract(a,b), "\n")
print(np.multiply(a,b), "\n")
print(np.divide(a,b), "\n")

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]] 

[[25  4 16  8  4]
 [14  4 26 13  8]
 [ 5 24 17 20  3]
 [14 16 10 15  4]
 [15 27 24  6  6]] 

[[26  7 21 15 13]
 [25 17 41 30 27]
 [26 47 42 47 32]
 [45 49 45 52 43]
 [56 70 69 53 55]] 

[[26  7 21 15 13]
 [25 17 41 30 27]
 [26 47 42 47 32]
 [45 49 45 52 43]
 [56 70 69 53 55]] 

[[-24  -1 -11  -1   5]
 [ -3   9 -11   4  11]
 [ 16  -1   8   7  26]
 [ 17  17  25  22  35]
 [ 26  16  21  41  43]] 

[[  25   12   80   56   36]
 [ 154   52  390  221  152]
 [ 105  552  425  540   87]
 [ 434  528  350  555  156]
 [ 615 1161 1080  282  294]] 

[[0.04       0.75       0.3125     0.875      2.25      ]
 [0.78571429 3.25       0.57692308 1.30769231 2.375     ]
 [4.2        0.95833333 1.47058824 1.35       9.66666667]
 [2.21428571 2.0625     3.5        2.46666667 9.75      ]
 [2.73333333 1.59259259 1.875      7.83333333 8.16666667]] 



In [82]:
a = np.arange(1, 50, 2).reshape(5,5)
print(a,"\n")
b = np.random.randint(1,28, size=(5,5))
print(b, "\n")
print(np.sqrt(a), "\n")
print(np.exp(a), "\n")
print(np.power(b,3), "\n")

print(np.max(a), " : ", np.min(a))
print(np.max(b, axis=0), " : ", np.min(b, axis=0))
print(np.max(b, axis=1), " : ", np.min(b, axis=1))

print(np.std(a), " : ", np.std(a, axis=0))
print(np.mean(a, axis=0), " : ", np.median(a, axis=0))
print(np.mean(a, axis=1), " : ", np.median(a, axis=1))

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]] 

[[ 1  3 26  8 24]
 [10 21 12 18  4]
 [ 3  4 19 26 21]
 [10 18  1 25 12]
 [ 9 14  2  5 16]] 

[[1.         1.73205081 2.23606798 2.64575131 3.        ]
 [3.31662479 3.60555128 3.87298335 4.12310563 4.35889894]
 [4.58257569 4.79583152 5.         5.19615242 5.38516481]
 [5.56776436 5.74456265 5.91607978 6.08276253 6.244998  ]
 [6.40312424 6.55743852 6.70820393 6.8556546  7.        ]] 

[[2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
  8.10308393e+03]
 [5.98741417e+04 4.42413392e+05 3.26901737e+06 2.41549528e+07
  1.78482301e+08]
 [1.31881573e+09 9.74480345e+09 7.20048993e+10 5.32048241e+11
  3.93133430e+12]
 [2.90488497e+13 2.14643580e+14 1.58601345e+15 1.17191424e+16
  8.65934004e+16]
 [6.39843494e+17 4.72783947e+18 3.49342711e+19 2.58131289e+20
  1.90734657e+21]] 

[[    1    27 17576   512 13824]
 [ 1000  9261  1728  5832    64]
 [   27    64  6859 17576  9261]
 [ 1000  5832     1

In [88]:
a = np.array([1, 2, 4])
print(a, "\n")
b = np.arange(9).reshape(3,3)
print(b, "\n")
c = np.arange(1, 10, 3).reshape(3, 1)
print(c, "\n")
print()
print(a + b)
print()
print(b + c)

[1 2 4] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[1]
 [4]
 [7]] 


[[ 1  3  6]
 [ 4  6  9]
 [ 7  9 12]]

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]


In [92]:
print(np.ones([4,4]) + np.array([0,1,2,3]))

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [94]:
!conda list pandas


# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
pandas                    0.23.4           py37h830ac7b_0  
